const express = require("express")
require("dotenv").config({ path: "./config/.env" })
const db = require("./config/db")
require("colors")
const cors = require("cors")
db()
const app = express()
const PORT = process.env.PORT || 5000
app.use(express.json())
app.use(express.static("public"))
// app.use(cors({ origin: ["http:localhost:5173", "http://127.0.0.1:5173"], methods: ["GET"] }))
app.use(cors())
app.use("/blog", require("./routes/BlogRoutes"))
app.listen(PORT, console.log(`server Runing http://localhost:${PORT}`.bgBlue))